# Generated by Django 4.2.4 on 2024-02-01 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_category_subscribers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='dateCreation',
            field=models.DateTimeField(),
        ),
    ]
